- name: Add Ansible Repository
  apt_repository:
    repo: "ppa:ansible/ansible"
  become: yes

- name: Install Ansible
  become: yes
  apt:
    update_cache: yes
    pkg:
    - ansible

- name: Install PyWinRM
  args:
    executable: /bin/bash
  become: yes
  shell: |
    pip install pywinrm
