- hosts: phantom
  gather_facts: False
  become: true
  
  vars_prompt:
  
  - name: phantom_community_username
    prompt: Enter Phantom community username
    unsafe: yes
    private: yes
    
  - name: phantom_community_password
    prompt: Enter Phantom community password
    unsafe: yes
    private: yes
  
  roles:
    - phantom
  
  tags: phantom